* VBA2Python[0/3]
** TODO Generate Cpp code to parse VBA in the future[0/3]
*** TODO Generate lex code[5/6]
   - [X] add test for lex for future maintain[0/0]
     - understand the std::forward
     - one project can export a header file, because there exists nameof(x) macro
   - [X] solve the conflict issue between TokType Terminal and RegularExpression[1/1]
     - [X] construct wrong DFA which doesn't have state result to Terminal
       - fine the Step struct
       - found: when Freeze, it has multiple result states for one step
       - Minimize<true> merge wrongly [2025-02-24 Mon]
       - fixed: in Minimize<true> worklist doesn't split accept states when specified <2025-02-25 Tue>
       - +actually is NFA2DFA issue, because one state to different states with same step+
   - [X] support more escaped char in Terminal and RegularExpression
     - regular expression for Terminal from "\"((\\\\[\"\\\\rn])|[^\"\n])*\"" to "\"((\\\\\")|[^\"\n])*\""(more simple, but handle escaped char wrongly)
     - in the 2nd one, it matches escaped char without length limit. For input: "\\" | "^", it will eat the second quote mark with previous slash, this is
     - not expect behavior. Only allow escape one char.
     - fixed: "\"((\\\\[^\n])|[^\"\n])*\"", better with not match slash in the right part: "\"((\\\\[^\n])|[^\\\\\"\n])*\""
     - write correct regular expression is hard <2025-02-25 Tue>
   - [X] fix generated code issue
     - [X] handle string terminal and regular expression terminal print 
     - [X] a alone quote char. Caused by wrong operation in AST construction
     - [X] use regular expression to represent DataRange <2025-02-25 Tue>
     - [X] escape the normal string to regular expression form
     - [X] fix regular expression using in ABNF file
     - [X] slash of regular expression in ABNF file need to be escaped in generated cpp code <2025-02-26 Wed>
   - [X] combine same terminal in generated grammar code(when use set<String> to store, it's done)
     - [X] give Terminal item with identical name in global scope
     - [X] use reference to share Terminals between GrammarTransformInfo
     - [X] should we share the OtherGrammars also? Yes, then we don't need many move code
     - [X] sub GrammarTransformInfo should be constructed by parent GrammarTransformInfo, to let parent control the relationship between them <2025-02-26 Wed>
   - [ ] check the generated grammar rule is correct 
*** TODO Generat parse code[0/2]
   - [ ] solve operator priority issue
** TODO Generate AST code
** TODO Write Transformer code to translate VBA to Python



